### PR TITLE
feat(uk-UA): add autotranslated locale uk-UA. Closes #209

### LINKED ISSUE #209: Locale request: uk-UA
Hey, I would like ask you to generate default localization data for Ukrainian language.

Since I am a native speaker, I can review PR and adjust the translation where needed.

Also, I've been meaning to explore the Studio in depth for a long time, so I'll kill two birds with one stone, will explore the project and help the community.

Thank you in advance,
Oleksii

- [X] I want to be added as maintainer

### PR DESCRIPTION
**Pull request by runeb**

### CODE REVIEW

**Comment by runeb** [comment]
Have a look at this initial translation to Ukrainian and please suggest any improvements if you have them, @fomazov 🙂

You can make suggestions right here in the PR, or through any other means like forks if you are more comfortable with that. We have added a quick guide in [CONTRIBUTING.md](https://github.com/sanity-io/locales/blob/main/CONTRIBUTING.md#suggesting-improvements) on how to easily use github.com itself to help improve languages.

**Comment by fomazov** [comment]
Hey @runeb, thanks for your help with raising this PR and including me in the [demo video](https://www.loom.com/share/f75d227a116c4df2a3c0d2b675842bec?sid=03c7d4b6-3d0a-4575-b65a-d5247368b30d) ✌️

As I mentioned in https://github.com/sanity-io/locales/issues/209, I want to explore a new language in Studio UI, after that I want to raise a new PR with suggestions against the current one.

So, I cloned the repo and start the project locally:

```
git clone git@github.com:sanity-io/locales.git
cd locales
pnpm install
pnpm run dev
```

Since I had already set up a sandbox project, I reused the `projectId` (first step) and removed the redundant locales leaving only one (second step)

Code_I7dPMjqQr7

Eventually, I started the monorepo instance 

```
pnpm run dev
```

The UI now contains elements in Ukrainian, but I'm confused by the fact that some names are left untranslated. 

Note the title of the browser tab (`Untitled`, it should be `Без назви`). 

chrome_yknjBIZyvh

I realise that this is partly due to the demonstration of the custom i18n plugin that we connected in the configuration (`i18nDemo`). 

But this block definitely needs to be translated and I see that we have value pairs for that:

chrome_TXKQFgdfGG

Code_Z4TQDRgLn2

My question is, perhaps I have built the project incorrectly and there are other options?

For example, I was thinking about using https://pnpm.io/cli/link to connect a not yet released Ukrainian locale, to my original sandbox project.

Thanks in advance, 
Oleksii

**Comment by runeb** [comment]
Thank you for your detailed and considered review, @fomazov! I have added a ticket for the document title string, looks like a missed string in our initial internationalization of core Studio code.

As to the menu items, these actually comes from the server and those strings (a little confusingly, I admit) are fallback titles in the event the menu contents could not load remotely. For now this area of the Studio will remain untranslated as a full translation here would require the rest of Sanity to support more locales in the content published from our servers.

Finding this oddity shows your dedication to doing a good and thorough review, and for that we are very grateful!

**Comment by runeb** [comment]
> For example, I was thinking about using https://pnpm.io/cli/link to connect a not yet released Ukrainian locale, to my original sandbox project.

Yes, you can build the plugin in this monorepo and link it into other projects you may have locally. Thats a great way to test the locale! `pnpm link` should work and the documentation for that command should apply here. Let me know if you meet any issues, and also whether you give a thumbs up or down on this initial locale translation so I can merge and release it.

**Comment by runeb** [comment]
@fomazov merging this PR now, if you had pending suggestions feel free to open a PR with those! Thanks again

**Pull request merged**
